name: ressat
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pillow
  - tqdm
  - anndata
  - pytorch
  - torchvision
  - notebook
  - ipykernel